import p0 from '../lib/r_ipgu_0.js'
import p1 from '../lib/r_ipgu_1.js'
import p1m from '../lib/r_ipgu_1m.js'
import p2 from '../lib/r_ipgu_2.js'
import p3 from '../lib/r_ipgu_3.js'
import p4 from '../lib/r_ipgu_4.js'
import p5a from '../lib/r_ipgu_5a.js'
import p5b from '../lib/r_ipgu_5b.js'
import p6a from '../lib/r_ipgu_6a.js'
import p6b from '../lib/r_ipgu_6b.js'
import p7a from '../lib/r_ipgu_7a.js'
import p7b from '../lib/r_ipgu_7b.js'
import p8a from '../lib/r_ipgu_8a.js'
import p8b from '../lib/r_ipgu_8b.js'
import p8m from '../lib/r_ipgu_8m.js'
import p9 from '../lib/r_ipgu_9.js'
export default function handler(req,res){const p1x=p1.slice(0,1432)+p1m+p1.slice(1432);const p8x=p8b.slice(0,1509)+p8m+p8b.slice(1509);const b=Buffer.from(p0+p1x+p2+p3+p4+p5a+p5b+p6a+p6b+p7a+p7b+p8a+p8x+p9,'base64');res.setHeader('Content-Type','image/jpeg');res.setHeader('Cache-Control','public,max-age=60');res.status(200).send(b)}
