import p0 from '../lib/r_ipgu_0.js'
import p1 from '../lib/r_ipgu_1.js'
import p1m from '../lib/r_ipgu_1m.js'
import p2 from '../lib/r_ipgu_2.js'
import p3 from '../lib/r_ipgu_3.js'
import p4 from '../lib/r_ipgu_4.js'
import p5 from '../lib/r_ipgu_5.js'
import p6 from '../lib/r_ipgu_6.js'
import p7 from '../lib/r_ipgu_7.js'
import p8 from '../lib/r_ipgu_8.js'
import p9 from '../lib/r_ipgu_9.js'
export default function handler(req,res){const p1x=p1.slice(0,1432)+p1m+p1.slice(1432);const b=Buffer.from(p0+p1x+p2+p3+p4+p5+p6+p7+p8+p9,'base64');res.setHeader('Content-Type','image/jpeg');res.setHeader('Cache-Control','public,max-age=60');res.status(200).send(b)}
